### ISSUE TITLE
Inject env variables from file

### ISSUE THREAD

**Issue by eloo** [unknwon/bra#22]
Hi,
i'm currently trying to get env variables injected from a file..
Like source .env or calling a script with an export.. but it seems that this is not possible?
Or how can this be done? Maybe anyone has an idea?

Thx

the only solution for now i found is to use a command like this
`source .env && bra run`

**Comment by unknwon** [comment]
Hi, I think the solution you currently have is pretty good. Each tool does it's own job perfectly!
