### ISSUE TITLE
Support symbolic links

### ISSUE THREAD

**Issue by marefr** [unknwon/bra#23]
Support watching and reloading when symbolic file link changes.

**Comment by unknwon** [comment]
Hi, what do you mean by "when symbolic file link changes"? The link itself or ...?

**Comment by marefr** [comment]
Given 
```bash
ln -s <source file> <target>
```

Where `<target>` is in the path of bra `watch_dirs`. If source file changes and are saved I would like bra to trigger a reload.

**Comment by unknwon** [comment]
Thanks, got it!

**Comment by marefr** [comment]
Opened https://github.com/Unknwon/com/pull/18 to first add support there for symbolic links when getting all sub directories.

**Comment by marefr** [comment]
As soon opened PR is accepted/merged I want to submit a PR for bra. I'm thinking that introducing a new setting to enable following symbolic links which by default is false (to be backward compatible). How does this sound?

**Comment by unknwon** [comment]
Merged!
