### ISSUE TITLE
How to pass arguments to bra?

### ISSUE THREAD

**Issue by mcoimbra** [unknwon/bra#26]
Hello,

Thanks for sharing this tool with the community.
I'm having a difficulty using bra - how may I pass arguments into bra's command handling?

For example, I want to watch the backend while developing [Grafana](https://github.com/grafana/grafana).
To do so, they recommend doing:

`bra run`

This led to the creation and usage of the following contents:

```
[run]
init_cmds = [
  ["go", "run", "build.go", "-dev", "build-server"],
        ["./bin/grafana-server", "cfg:app_mode=development"]
]
watch_all = true
follow_symlinks = true
watch_dirs = [
        "$WORKDIR/pkg",
        "$WORKDIR/public/views",
        "$WORKDIR/conf",
]
watch_exts = [".go", ".ini", ".toml", ".template.html"]
build_delay = 1500
cmds = [
  ["go", "run", "build.go", "-dev", "build-server"],
        ["./bin/grafana-server", "cfg:app_mode=development"]
]
```

This works fine for starting everything with default values, but what if i wanted to run `grafana-server` with arguments like this:

`grafana-server -config $HOME/.grafana/grafana.ini -homepath $HOME/go/src/github.com/grafana/grafana/
`
What would be the correct way to edit the `.bra.toml` file to enable argument passing like this?

Thank you very much.

**Comment by unknwon** [comment]
Hi, I don't think you can. A better solution would be write a Makefile, use it's builtin mechanism to accept command line arguments, and call `make xx` in `.bra.toml`.

**Comment by Unknwon** [comment]
.

**Comment by unknwon** [comment]
Or, if the values of CLI flags do not change, just update the line:

```
 ["./bin/grafana-server", "cfg:app_mode=development"]
```

with actual value. ($HOME must be expanded, bra does not read env vars)
