### ISSUE TITLE
Golang/lib/src/github.com/Unknwon/bra/cmd/run.go:204:17: undefined: com.LgetAllSubDirs

### ISSUE THREAD

**Issue by SevenChen** [unknwon/bra#27]
Golang/lib/src/github.com/Unknwon/bra/cmd/run.go:204:17: undefined: com.LgetAllSubDirs

**Comment by unknwon** [comment]
https://github.com/Unknwon/com/blob/41959bdd855fb7db467f78865d5f9044507df1cd/dir.go#L137
