### ISSUE TITLE
[feature request] Ignore file pattern

### ISSUE THREAD

**Issue by exu** [unknwon/bra#3]
It would be great to have file pattern ignore option, what do you think about it?

**Comment by unknwon** [comment]
Yes, I'm thinking the same thing, plan to add add a key named `ignore_files`, and allows a list of regexp, how do you think?

**Comment by exu** [comment]
@Unknwon it would be great!

**Comment by unknwon** [comment]
@exu code has been pushed, please help test!

**Comment by exu** [comment]
@Unknwon working, thanks alot :D

**Comment by unknwon** [comment]
No problem! :beer:
