### ISSUE TITLE
How to deal with file without extension

### ISSUE THREAD

**Issue by stefancocora** [unknwon/bra#5]
I have in directories multiple files that `bra` is watching, captured in the `.bra.toml`

``` bash
...
watch_exts = [".tf", ".tfvars", ".tpl", ".toml"]                # Extensions to watch
...
```

I would also like to add to the list of watched files a file without an extention, for example a file called `Rakefile` or `Gemfile`

Is that possible with the current bra `Bra version 0.3.4.0911` ?

**Comment by unknwon** [comment]
The program actually checks the suffix of a string, so just put full file name should work. :D

**Comment by stefancocora** [comment]
I've tested it and it works as you say !
Thanks

**Comment by unknwon** [comment]
💯
