### ISSUE TITLE
求助：sync命令

### ISSUE THREAD

**Issue by cgyy** [unknwon/bra#9]
你好，安装bra之后发现比文档多了一个bra sync 子命令，请问这个是干什么用的？

**Comment by unknwon** [comment]
。。本来是自己用来同步两个端点的文件的，但是底层依赖的fsnotify在mac上拷贝大文件的时候事件捕捉有点问题。。没好意思公开这个功能。。

**Comment by cgyy** [comment]
soga  ^_^

**Comment by unknwon** [comment]
:sweat_smile:
